---
apiVersion: v1
data:
  loggie.yml: |-
      loggie:
        defaults:
          sources:
          - type: file
            fieldsUnderRoot: true
            addonMeta: true
            fields:
              cluster_name: {{ .Values.clustername }}
          interceptors:
          - type: schema
            order: 600
            addMeta:
              timestamp:
                key: "@timestamp"
            remap:
              body:
                key: message
          - type: transformer
            actions:
              - action: copy(state.filename, filename)
              - action: copy(state.source, source)
              - action: del(state)
          sink:
            type: elasticsearch
            hosts: [{{ .Values.elasticsearch.address | quote }}]
            index: "log-${+YYYY.MM.DD}"
            username: {{ .Values.elasticsearch.username }}
            password: {{ .Values.elasticsearch.password }}
            etype: _doc
        reload:
          enabled: true
          period: 10s
        monitor:
          logger:
            period: 30s
            enabled: true
          listeners:
            filesource: ~
            filewatcher: ~
            reload: ~
            sink: ~
            queue: ~
            pipeline: ~
        discovery:
          enabled: true
          kubernetes:
            containerRuntime: {{ .Values.containerRuntime }}
            rootFsCollectionEnabled: {{ .Values.rootFsCollectionEnabled }}
            parseStdout: true
            k8sFields:
              logconfig: "${_k8s.logconfig}"
              namespace: "${_k8s.pod.namespace}"
              nodename: "${_k8s.node.name}"
              pod_name: "${_k8s.pod.name}"
              containername: "${_k8s.pod.container.name}"

        http:
          enabled: true
          port: 9196

kind: ConfigMap
metadata:
  name: loggie-config
  namespace: {{ .Release.Namespace }}
